# Generated by Django 4.2.4 on 2023-09-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=150, null=True, verbose_name='ответ')),
                ('user_answer', models.BooleanField(default=False, verbose_name='ответ пользователя')),
                ('is_correct_answer', models.BooleanField(default=False, verbose_name='правильный ответ')),
                ('is_user_correct', models.BooleanField(default=False, verbose_name='верный ли ответ пользователя')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'ответы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=255, null=True, verbose_name='вопрос')),
                ('is_active', models.BooleanField(default=True, verbose_name='опубликован')),
                ('is_finished', models.BooleanField(default=False, verbose_name='завершено')),
                ('answer', models.ManyToManyField(to='study.answers')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_m', models.CharField(blank=True, max_length=50, null=True, verbose_name='название')),
                ('is_finished', models.BooleanField(default=False, verbose_name='завершен')),
                ('count_questions', models.IntegerField(default=0, verbose_name='количество вопросов')),
                ('percent_complete', models.FloatField(default=0.0, verbose_name='процент выполнения')),
                ('question', models.ManyToManyField(to='study.question')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='раздел')),
                ('about', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('materials', models.ManyToManyField(to='study.materials')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
            },
        ),
    ]
