# Generated by Django 4.2.4 on 2023-09-19 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
