# Generated by Django 4.2.4 on 2023-09-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_remove_item_materials_item_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='question',
        ),
        migrations.AddField(
            model_name='materials',
            name='question',
            field=models.ManyToManyField(blank=True, null=True, to='study.questions'),
        ),
    ]
