# Generated by Django 4.2.4 on 2023-09-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_remove_materials_question_materials_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ManyToManyField(to='study.questions'),
        ),
    ]
