# Generated by Django 4.2.4 on 2023-09-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_remove_answers_question_answers_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.ManyToManyField(to='study.answers'),
        ),
    ]
