# Generated by Django 4.2.4 on 2023-09-08 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0008_alter_answers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='materials',
            field=models.ManyToManyField(to='study.materials'),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materials',
            name='question',
            field=models.ManyToManyField(to='study.question'),
        ),
    ]
