# Generated by Django 4.2.4 on 2023-09-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_alter_item_materials_alter_item_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ManyToManyField(to='study.question'),
        ),
    ]
