# Generated by Django 4.2.4 on 2023-09-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usercustom',
            managers=[
            ],
        ),
    ]
